name: Build Docker images

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [apache, fpm]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build ${{ matrix.image }} image
        uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.image }}/Dockerfile
          push: true
          tags: ${{ vars.REGISTRY }}/mautic/mautic:v4-${{ matrix.image }}
